name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: AIzaSyDcbXrv8DNjEU15H7o6lWwJtMSGTkvfTxU
          VITE_FIREBASE_AUTH_DOMAIN: moneyos-550b3.firebaseapp.com
          VITE_FIREBASE_PROJECT_ID: moneyos-550b3
          VITE_FIREBASE_STORAGE_BUCKET: moneyos-550b3.firebasestorage.app
          VITE_FIREBASE_MESSAGING_SENDER_ID: "120039087701"
          VITE_FIREBASE_APP_ID: 1:120039087701:web:db0fb20907b5e51e6cfedc

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MONEYOS_550B3 }}
          channelId: live
          projectId: moneyos-550b3
